version: '3.8'

services:
  flask:
    build:
      context: ./
    ports:
      - 5000:5000
  
  mysql:
    image: mysql:8.0.31
    ports:
      - '30000:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080